apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qlearning-app
  namespace: argocd  # ArgoCD must watch this namespace
spec:
  project: default

  source:
    repoURL: 'https://github.com/ashu304-ops/dampersproject.git'
    targetRevision: HEAD
    path: .
    # You can specify a subfolder if your manifests are not in the root

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Optional: creates namespace if missing
