#include "SuspensionController.hpp"
#include "ComfortStrategy.hpp"

SuspensionController::SuspensionController(
    ISensorReader& sensor,
    ICoilDriver& coil,
    ITelemetryLogger& logger) noexcept
    : sensor_(sensor),
      coil_(coil),
      logger_(logger) {}

void SuspensionController::setStrategy(
    std::unique_ptr<IDampingStrategy> strategy) noexcept {
    strategy_ = std::move(strategy);
}

void SuspensionController::runCycle(float ambientTempC) noexcept {
    lastSensorError_ = SensorError::None;
    lastCoilError_ = CoilError::None;
    safeMode_ = false;

    // ------------------------------------------------------------
    // Simulated thermal model
    //
    // Control loop runs at 100 Hz, so each cycle is approximately
    // 0.01 seconds.
    //
    // Higher coil current -> more heat.
    // Temperature naturally cools toward ambient when current falls.
    // ------------------------------------------------------------
    constexpr float dt = 0.01f;

    const float currentSquared =
        lastRequestedCurrentA_ * lastRequestedCurrentA_;

    // Heating generated by the electromagnetic coil.
    const float heatingRate = currentSquared * 15.0f;

    // Natural cooling toward ambient temperature.
    const float coolingRate =
        (lastTemperatureC_ - ambientTempC) * 0.40f;

    lastTemperatureC_ +=
        (heatingRate - coolingRate) * dt;

    // Keep the simulation physically reasonable.
    if (lastTemperatureC_ < ambientTempC) {
        lastTemperatureC_ = ambientTempC;
    }

    if (lastTemperatureC_ > 150.0f) {
        lastTemperatureC_ = 150.0f;
    }

    // Thermal safety check.
    if (lastTemperatureC_ >= 150.0f) {
        enterSafeMode(SensorError::HardwareFault);
        return;
    }

    if (!strategy_) {
        strategy_ = std::make_unique<ComfortStrategy>();
    }

    // ------------------------------------------------------------
    // Read acceleration sensor
    // ------------------------------------------------------------
    const SensorReadResult sensorResult = sensor_.read();

    lastAccelerationG_ = sensorResult.accelerationG;
    lastSensorError_ = sensorResult.error;

    if (!sensorResult.success()) {
        enterSafeMode(sensorResult.error);
        return;
    }

    // ------------------------------------------------------------
    // Filter sensor value
    // ------------------------------------------------------------
    const float filteredG =
        filter_.filter(sensorResult.accelerationG);

    // ------------------------------------------------------------
    // Calculate damping force
    // ------------------------------------------------------------
    const float forceN =
        strategy_->calculateForceN(filteredG);

    lastForceN_ = forceN;

    // Store force history.
    forceHistory_.push(forceN);

    // ------------------------------------------------------------
    // Convert force to requested coil current
    // ------------------------------------------------------------
    const float requestedCurrentA =
        forceN * 0.01f;

    lastRequestedCurrentA_ =
        requestedCurrentA;

    // ------------------------------------------------------------
    // Apply current using the simulated coil temperature
    // ------------------------------------------------------------
    const CoilResult coilResult =
        coil_.setCurrent(
            requestedCurrentA,
            lastTemperatureC_);

    lastCoilError_ = coilResult.error;

    if (!coilResult.success()) {
        enterSafeMode(SensorError::HardwareFault);
        return;
    }

    // Normal operation.
    logger_.record(
        sensorResult,
        coilResult,
        forceN);
}

void SuspensionController::enterSafeMode(
    SensorError error) noexcept {

    safeMode_ = true;
    lastSensorError_ = error;

    // Do NOT reset temperature to 25 C here.
    // The thermal state should remain visible in telemetry.
    const CoilResult result =
        coil_.setCurrent(
            0.0f,
            lastTemperatureC_);

    lastCoilError_ = result.error;

    logger_.recordSensorError(error);
}
